# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Bio"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "papers/"
  weight = 20


[[main]]
  name = "Projects"
  url = "projects/"
  weight = 30

[[main]]
  name = "Activities"
  url = "activities/"
  weight = 40


[[main]]
  name = "Teaching"
  url = "teaching/"
  weight = 50

[[main]]
  name = "Awards"
  url = "awards/"
  weight = 60

[[main]]
  name = "Students"
  url = "students/"
  weight = 70

[[main]]
  name = "Recruitment"
  url = "recruitment/"
  weight = 80



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
